# Expression generated by update.sh; do not edit it by hand!
{
  stdenv,
  callPackage,
  ...
} @ args: let
  pname = "brave";
  version = "1.95.78";

  allArchives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-browser-nightly_${version}_amd64.deb";
      hash = "sha256-aB2XW3hLSmiCBgVXPX+tmwr54Do/Va5Zh7grLlj2OCg=";
    };
  };

  archive =
    if builtins.hasAttr stdenv.system allArchives
    then allArchives.${stdenv.system}
    else throw "Unsupported platform.";
in
  callPackage ./make-brave.nix (removeAttrs args ["callPackage"]) (
    archive
    // {
      inherit pname version;
    }
  )
